"""add created_by to companies

Revision ID: 76b45d937cfd
Revises: fd0902880c1e
Create Date: 2026-07-20 23:24:50.232390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76b45d937cfd'
down_revision: Union[str, None] = 'fd0902880c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'companies', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'created_by')
    # ### end Alembic commands ###
